global:
  values:
    paths:
      workflow_generator:
        - .github/overlays/**
    public: true
    ytt:
      template_paths: remote/ytt,this/.github/overlays
  workflows:
    - file: library.yml
    - file: publish.yml
    - file: workflow-generator.yml
