name: Library
"on":
  push:
    branches:
    - main
    paths:
    - .github/workflows/library.yml
    - '**/*.{js,ts}'
  pull_request:
    paths:
    - .github/workflows/library.yml
    - '**/*.{js,ts}'
  workflow_dispatch: null
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.17.1
    - name: Checkout current git repository
      uses: actions/checkout@v2
    - name: Install yarn dependencies
      run: yarn install --immutable
    - name: Run lint
      id: yarn_lint
      run: yarn lint
    - name: Run test
      id: yarn_test
      run: yarn test
    - name: Run build
      id: yarn_build
      run: yarn build
  draft-release:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Create release draft
      uses: darioblanco/release-wizard@main
      with:
        draft: true
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
