name: NPM Publish
"on":
  release:
    types:
    - published
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current git repository
      uses: actions/checkout@v2
    - name: Install yarn dependencies
      run: yarn install --immutable
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.17.1
        registry-url: https://npm.pkg.github.com
        scope: '@kirinus'
    - name: Run build
      id: yarn_build
      run: yarn build
    - name: Set release version
      id: vars
      run: echo ::set-output name=tag::$(echo ${{ github.event.release.tag_name }} | cut -d "v" -f 2)
    - name: Publish the package
      run: |
        npm --no-git-tag-version version $RELEASE_VERSION
        npm config set registry https://npm.pkg.github.com
        echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
        npm publish --access restricted
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
